### ISSUE TITLE
Visual delete error

### ISSUE THREAD

**Issue by lvim-tech** [tristone13th/lspmark.nvim#1]
Visual delete error

```
E5108: Error executing lua: ...l/share/nvim/lazy/lspmark.nvim/lua/lspmark/bookmarks.lua:499: bad argument #1 to 'sub' (string expected, got nil)
stack traceback:
	[C]: in function 'sub'
	...l/share/nvim/lazy/lspmark.nvim/lua/lspmark/bookmarks.lua:499: in function 'get_visual_selection'
	...l/share/nvim/lazy/lspmark.nvim/lua/lspmark/bookmarks.lua:549: in function 'delete_visual_selection'
```

Additionally, upon restarting Neovim, the bookmarks do not load.

**Comment by tristone13th** [comment]
Thanks for reporting the bug, could you provide more hints on how to reproduce the error log? it works fine on my side.

> Additionally, upon restarting Neovim, the bookmarks do not load.

The bookmarks are organized project-wise so they will only be loaded when changing to the cwd that has bookmarks associated with it.

**Comment by lvim-tech** [comment]
1. Select visual
2. Press `d`
3. `:messages` : error text

**Comment by tristone13th** [comment]
> 1. Select visual
> 2. Press `d`
> 3. `:messages` : error text

Is this 100% reproducible?

**Comment by lvim-tech** [comment]
```
-- bookmarks.lua file
	-- get all lines of text
	local lines = vim.api.nvim_buf_get_lines(0, start_line - 1, end_line, false)
	vim.notify(vim.inspect(lines))
```
result = {}

**Comment by tristone13th** [comment]
Maybe you bind the key in normal mode to this function such as ["n|d"] rather than in visual mode ["v|d"], could you have a check?

**Comment by lvim-tech** [comment]
```        
vim.keymap.set("v", "d", function()
    require("lspmark.bookmarks").delete_visual_selection()
end)
```

**Comment by tristone13th** [comment]
Could you show me your Lua config? I still cannot reproduce it on my side.
