### ISSUE TITLE
Collaboration with other people

### ISSUE THREAD

**Issue by DeadlySquad13** [tristone13th/lspmark.nvim#10]
Hello! Thanks for you plugin, I'm considering to integrate it into my workflow. The idea of persistent marks is really charming!
But do they persist when collaborating with other people? On one hand, I see it's LSP based so it *may* be possible. But, on the other hand, this plugin requires calling API during paste and delete meaning that the marks will be ruined once someone moves a code without these callbacks? Can you please clarify it? Seems like a real deal-breaker to me (or huge feature if it actually works).

**Comment by tristone13th** [comment]
Hi @DeadlySquad13 , I don't think this plugin is designed oriented for collaborating so I cannot guarantee that it will work in this case.
