### ISSUE TITLE
[Bug?] Odd behavior adding bookmark to keymaps (multiple added in different location)

### ISSUE THREAD

**Issue by 956MB** [tristone13th/lspmark.nvim#2]
![Screen Recording 2024-06-21 at 1 (3)](https://github.com/tristone13th/lspmark.nvim/assets/39519792/0fbcdb5b-a719-4e31-9a62-48596de6a30a)

Steps happening in the gif ^:

1. `<leader>tl`: Show bookmarks in Telescope
2. `<leader>tb`: Toggle bookmark on line
3. `<C-s>`: Save.
4. `<leader>tl`: Show bookmarks, single bookmark shows up fine.
5. `<leader>tb`: Toggle bookmark on `local function map(...)` function.
6. `<C-s>`: Save... bookmark indicator on the left disappears.
7. `<leader>tl`: Show bookmarks. Two new bookmarks show up in the list, neither of them the line I set a bookmark on, and both are on a `map` function being _called_ at the very end of the file. You can see the bookmark indicators on lines `237` and `239`.
8. `<leader>tb`: Toggle bookmark on a `map` on line `15`.
9. `<C-s>`: Save.
10. `<leader>tl`: The indicator again disappears and another entry shows up in the Telescope list of bookmarks. Seems like this new entry is again on the last line/function in the file, though only the two indicators remain on `237` and `239`.

`plugins/ui.lua`:

```lua
{
    'tristone13th/lspmark.nvim',
    config = function()
        require('lspmark').setup()
        require('telescope').load_extension 'lspmark'
    end,
},
```

`config/keymaps.lua`:

```lua
local function map(mode, lhs, rhs, opts)
    opts = opts or {}
    opts.silent = opts.silent ~= false
    vim.keymap.set(mode, lhs, rhs, opts)
end

map('n', '9', '$', { noremap = true, desc = 'Go to end of line' })

map('n', '<C-a>', 'ggVG', { desc = 'Select [A]ll' })

-- Lspmark.nvim
map('n', 'p', function()
    require('lspmark.bookmarks').paste_text()
end, { desc = 'Lspmark [P]aste' })
map('n', '<leader>tb', function()
    require('lspmark.bookmarks').toggle_bookmark()
end, { desc = 'Lspmark [T]oggle [B]ookmark' })
map('n', '<leader>tl', ':Telescope lspmark<CR>', { desc = 'Toggle [L]spmark [T]elescope' })
map('v', 'd', function()
    require('lspmark.bookmarks').delete_visual_selection()
end, { desc = 'Lspmark [D]elete visual selection' })
map('n', 'dd', function()
    require('lspmark.bookmarks').delete_line()
end, { desc = 'Lspmark [D]elete line' })
```

Maybe it's something with my `map` function, which follows the format seen above, or it's some other part of my config I have wrong, I'm not sure. Using the bookmarks in other lua files in and out of my dotfiles seems to work fine though. Like just inside a plugin's repo it doesn't seem to have the same 'duplicate incorrect bookmarks' thing.

```lua
NVIM v0.9.5
```

**Comment by 956MB** [comment]
![Screen Recording 2024-06-21 at 3](https://github.com/tristone13th/lspmark.nvim/assets/39519792/ce815e9f-afdf-47d4-8348-9e3cf86b9ac7)

Other minor thing I noticed (not sure if it's expected behavior or not). When adding a bookmark to the top of this loop it adds a second to the `end` of it as well. When trying to remove the second bookmark on the `end` of the loop, then saving, it's added back. Also when toggling a bookmark on the single `map(...)` line inside the loop, a second bookmark is again added to `end`.

Again, not sure if it's expected or not... and please tell me if it's something to do with the way I've written things :|

**Comment by tristone13th** [comment]
Thanks for reporting this bug! I can reproduce it using your file config/keymaps.lua, but I may need some time to debug and fix this.

**Comment by tristone13th** [comment]
I see, that's because (symbol kind, symbol name) couldn't identify a unique symbol in a text document, the anonymous functions in each `map` function call are both assigned a name `map` which conflicts with the `map` function defined at the beginning, I need to find a way to fix this, maybe refresh the internal representation of each symbol.

**Comment by tristone13th** [comment]
#5 should fix this.
