### ISSUE TITLE
focus back to the opened buffer when bookmark selected instead of opening a new buffer

### ISSUE THREAD

**Issue by i3d** [tristone13th/lspmark.nvim#4]
Looks like the current behavior is simply just open up a new buffer whenever a bookmark is selected from `:Telescope lspmark`. It would be much nicer if the behavior can be that if the bookmark is pointing to an existing opened buffer, then just focus on that buffer and put the cursor on the marker. This way, for any opened buffers, there is no need to keep opening new buffers. When switch back and forth b/w opened buffers and their marks, the current behavior seems going to open up quite a lot of buffers.

**Comment by tristone13th** [comment]
Cannot reproduce this, could you give more details, e.g., your lua configs or some recordings?
